### ISSUE TITLE
макет: добавить логотип  в левый верхний угол

### ISSUE THREAD

**Issue by epogrebnyak** [finec-mgimo/preview#1]
https://squidfunk.github.io/mkdocs-material/getting-started/#logo

1. вывести какой-нибудь прямоугольный логотип 
2. дорисовать картинку

**Comment by epogrebnyak** [comment]
- Вместо 
![изображение](https://user-images.githubusercontent.com/9265326/82738927-1b534380-9d44-11ea-8d45-2dd360f5d861.png) может быть только svg изображение или какой-то растр?

Оформление:

- нам нужен какой-то белый логотип на синем фоне, чтобы поставить что-то свое?
- как будет смотреться на этом месте какой-то из [имеющихся логотипов](https://epogrebnyak.github.io/finec/gallery/) на с белым бэкграундом?
- может быть выбираем какой-то символ другой из шрифтов типа FontAwesome?

**Comment by kyrsquir** [comment]
Можно растр, но выглядит так себе:

![image](https://user-images.githubusercontent.com/10961196/82739213-80a83400-9d46-11ea-8315-870b59b4e146.png)

Что-то различимо только если сделать лого на всю высоту хедера и весь navbar вправо подвинуть:

![image](https://user-images.githubusercontent.com/10961196/82739248-d2e95500-9d46-11ea-9b4e-53a9bb6a84e8.png)

**Comment by epogrebnyak** [comment]
фактически нам нужен логотип на синем фоне, правильно?

**Comment by epogrebnyak** [comment]
![изображение](https://user-images.githubusercontent.com/9265326/82739343-91a57500-9d47-11ea-86f8-154c5c4478a1.png)

**Comment by kyrsquir** [comment]
Ну желательно, но полностью проблему это не решит. Если логотип будет такой же по сложности, то нижний текст не будет видно так и так

**Comment by epogrebnyak** [comment]
> 
> 
> ![изображение](https://user-images.githubusercontent.com/9265326/82739343-91a57500-9d47-11ea-86f8-154c5c4478a1.png)

Этот еще и меняет вид при наведении мышки. Это SVG?

**Comment by epogrebnyak** [comment]
> 
> 
> Ну желательно, но полностью проблему это не решит. Если логотип будет такой же по сложности, то нижний текст не будет видно так и так

А как путь к нему прописывать вы знаете?

**Comment by kyrsquir** [comment]
> Этот еще и меняет вид при наведении мышки. Это SVG?

У них конкретно да, но такой эффект можно и для растра сделать. Просто `opacity` меняется.

> А как путь к нему прописывать вы знаете?

Ну да, я же скриншот скинул из браузера)

**Comment by epogrebnyak** [comment]
А размеры какие оптимальные для логотипа, чтобы не сильно растягивал? Я хочу отдельный заказ на него сделать: SVG видимо лучше чем растр, и какой размер у него должен быть?

**Comment by kyrsquir** [comment]
SVG на то и **Scalable** Vector Graphics, что размер там не принципиален в отличие от растра. Он растягивается как угодно. Принципиально только соотношение сторон.

**Comment by kyrsquir** [comment]
Вот вроде лого в SVG нагуглилось. Не подойдёт?
[MGIMO_University-ru.svg.zip](https://github.com/epogrebnyak/finec/files/4672455/MGIMO_University-ru.svg.zip)

**Comment by epogrebnyak** [comment]
> Вот вроде лого в SVG нагуглилось. Не подойдёт?
> [MGIMO_University-ru.svg.zip](https://github.com/epogrebnyak/finec/files/4672455/MGIMO_University-ru.svg.zip)

Честно говоря, не знаю как его посмотреть. Думаю подойдет, особенно если нет надписи внизу.

**Comment by epogrebnyak** [comment]
Предлагаю поставить как временный вариант.

**Comment by kyrsquir** [comment]
Я могу отредактировать его немного в пределах разумного. Поменять цвета, убрать лишние элементы.

**Comment by epogrebnyak** [comment]
> Я могу отредактировать его немного в пределах разумного. Поменять цвета, убрать лишние элементы.

Было бы здорово подредактировать, но сильно не углубляясь.  Логотипы можно бесконечно совершенствовать.

**Comment by kyrsquir** [comment]
Вот так можно. Нижнюю надпись убрать не меняя саму иконку не так просто, она объединена в один SVG path с частью самой иконки.
![image](https://user-images.githubusercontent.com/10961196/82739977-23fc4780-9d4d-11ea-9c09-359f55ce7a3b.png)
В браузере слово "университет" вполне читаемо.

**Comment by epogrebnyak** [comment]
> В браузере слово "университет" вполне читаемо.

Проблема с Университет в том, что нам нужно вместо него "Кампус Одинцово".  

Может поставим https://github.com/epogrebnyak/finec/blob/master/source/img/logo-blind.png . Тут про Одинцово есть, хотя и не "Кампус", а "Филиал".

**Comment by kyrsquir** [comment]
Поставил. В браузере выглядит довольно замыленным
![image](https://user-images.githubusercontent.com/10961196/82740176-ff08d400-9d4e-11ea-92c0-78d5460e1639.png)

Если не принципиально, каким шрифтом написано ОДИНЦОВСКИЙ ФИЛИАЛ (такой текст должен быть?), то я могу попробовать в SVG это добавить, если хотите.

**Comment by epogrebnyak** [comment]
> Если не принципиально, каким шрифтом написано ОДИНЦОВСКИЙ ФИЛИАЛ (такой текст должен быть?), то я могу попробовать в SVG это добавить, если хотите.

Предлагаю написать:

```
МГИМО 
Кампус Одинцово 
```
Шрифт что-то желательно похожее, но какой там точно мы не знаем.

**Comment by kyrsquir** [comment]
С подбором шрифта пришлось повозиться. Вот такие варианты получились:

![image](https://user-images.githubusercontent.com/10961196/82741501-2c5b7f00-9d5b-11ea-9d77-e2dc15dee59f.png)

![image](https://user-images.githubusercontent.com/10961196/82741561-139f9900-9d5c-11ea-89b9-78322cb1793f.png)

**Comment by kyrsquir** [comment]
Закоммитил второй вариант

**Comment by kyrsquir** [comment]
А, при скроллинге header схлопывается... не заметил.
Убрал надпись, уменьшил лого, закоммитил.

**Comment by epogrebnyak** [comment]
Есть какой-то способ дать чуть больше места над верхним краем логотипа (не трогая html)? Сейчас ветки упираются прям в край браузера.

![изображение](https://user-images.githubusercontent.com/9265326/82750847-c7844100-9dbb-11ea-8897-6312675faceb.png)

**Comment by epogrebnyak** [comment]
Достаточно верхнего поля в 5 пикселей, мне кажется

**Comment by kyrsquir** [comment]
Сейчас так
![image](https://user-images.githubusercontent.com/10961196/82754708-797d3680-9dd7-11ea-92df-ba73464bc3c0.png)

5px много наверное
![image](https://user-images.githubusercontent.com/10961196/82754694-5eaac200-9dd7-11ea-8dbf-0a26b5521a48.png)
