### ISSUE TITLE
стандартное представление для сотрудника

### ISSUE THREAD

**Issue by epogrebnyak** [finec-mgimo/preview#13]
Нужен вариант представления сотрудника с фото.

Василюк Татьяна Николаевна

![](https://odin.mgimo.ru/images/vasiluktn.jpg)
Заведующий кафедрой менеджмента
Кандидат экономических наук
Доцент
Образование: МГУ им. М.В. Ломоносова
Стаж научно-педагогической работы: В высших учебных заведениях работает с 1980 года
Научные и учебные издания: Автор более 50 трудов.
Кабинет 424

**Comment by epogrebnyak** [comment]
Для стандартизации размеров фото - может их на какой-то сторонний сервис выкладывать?

**Comment by epogrebnyak** [comment]
Нам неплохо бы слева фото, справа - информация о человеке, видимо для этго нужны всавки html, в markdown таблице видимо не получится.

![изображение](https://user-images.githubusercontent.com/9265326/82754757-d678ec80-9dd7-11ea-8475-3f7299286f8c.png)

**Comment by epogrebnyak** [comment]
Общая идея - структура оформления должна быть для ввода новых данных и повтора на других сотрудников, быть не очень сложной.

**Comment by epogrebnyak** [comment]
Может быть вставить фото с заданным обтеканием текста (например, фото сносится справа вбок), тогда не надо добавлять таблицы

**Comment by kyrsquir** [comment]
Речь идёт о разделах Сотрудники -> Руководство и Сотрудники -> Деканат?

**Comment by epogrebnyak** [comment]
В первую очередь этот файл: 

https://github.com/epogrebnyak/finec/blob/master/source/people/principals.md

**Comment by kyrsquir** [comment]
Я пытаюсь найти что-то связанное с созданием своих components или partials, правильно было бы так это сделать. Пока нашёл только возможность заменить существующий partial. Вы не встречали подобного в документации?

**Comment by epogrebnyak** [comment]
Задачи я вижу две: 


- [ ] найти способ изменить позицию фотографий (обтекание текстом) 
- [ ] найти способ форматировать фотографии под один размер

**Comment by epogrebnyak** [comment]
> Я пытаюсь найти что-то связанное с созданием своих components или partials, правильно было бы так это сделать. Пока нашёл только возможность заменить существующий partial. Вы не встречали подобного в документации?

partials хорошо реализован в hugo, а в теме Academic также есть способ линковать людей, но это другой генератор, не mdocs

**Comment by epogrebnyak** [comment]
В restructured text тоже есть способ задавать позицию рисунка, может можно на тэг `img` вставлять какой-то класс добавлять и через css им управлять? 

C partials возможно чище, но для этого темы mkdocs надо хорошо знать.

**Comment by kyrsquir** [comment]
Ну вы же ещё хотели удобство редактирования и добавления новых людей. Тогда стоит попробовать partial дожать. А как называется используемая сейчас тема и где посмотреть, что в неё входит? На уровне `mkdocs` и `mkdocs-material` я нужного функционала не вижу, может в теме что-то есть?

**Comment by kyrsquir** [comment]
Или `mkdocs-material` это и есть тема и более конкретного ничего нет?

**Comment by epogrebnyak** [comment]
Mkdocs-material  это и есть тема.

**Comment by kyrsquir** [comment]
Вот такой вариант есть на флоатах

![image](https://user-images.githubusercontent.com/10961196/82764508-e7e1e900-9e17-11ea-9234-343a8dedcd34.png)
![image](https://user-images.githubusercontent.com/10961196/82764501-d4368280-9e17-11ea-943c-2e52aedbe0f1.png)

**Comment by kyrsquir** [comment]
CSS 297d5d22ee066c26827581230bcd57c0c829fc92
