### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by epogrebnyak** [finec-mgimo/preview#18]
- [x] Найти возможность поменять favicon (прописывается в mkdocs)
- [x] Подобрать другой символ (либо символ из шрифтов, либо какой-то упрощенный логотип)
- [x] Выбрать цвет (синий как у полоски+белый)

**Comment by kyrsquir** [comment]
![image](https://user-images.githubusercontent.com/10961196/82812092-e3124900-9e9a-11ea-8c62-f124c08f1c41.png)
Пойдёт?

**Comment by epogrebnyak** [comment]
Желательно более плоский, эллипсоид, не шарик.

**Comment by kyrsquir** [comment]
Фавиконка вписывается в квадрат. В данном случае это автоматически произошло как я понимаю, я ту же иконку, что на лого в углу поставил. Давайте закоммичу, посмотрите вживую

**Comment by kyrsquir** [comment]
f67518302b6eb0e952809c6c03c06532a84acb03

**Comment by epogrebnyak** [comment]
Может быть png все-таки? svg еще и подгружается долго.

**Comment by epogrebnyak** [comment]
Там для favicon векторы не нужны, она все время одного размера.

**Comment by kyrsquir** [comment]
Сначала поставил png, она ощутимо более размыто выглядела. Сами попробуйте.
Подгружаться svg долго вряд ли может, размер файла svg 7kb.

**Comment by epogrebnyak** [comment]
> Сами попробуйте.

Имя файла?

**Comment by kyrsquir** [comment]
`transparent.png`

**Comment by epogrebnyak** [comment]
https://www.emergeinteractive.com/insights/detail/the-essentials-of-favicons/
