### ISSUE TITLE
set image for Whatsapp link sharing

### ISSUE THREAD

**Issue by epogrebnyak** [finec-mgimo/preview#19]
При пересылки ссылки на сайт в мессенджерах подцепляется картинка с первой страницы, но она для этого не отцентрирована. 

- [ ] Найти как указать в явном виде такую картинку
- [ ] Подготовить и подцепить картинку
- [ ] Протестировать в вотсапп

**Comment by kyrsquir** [comment]
![photo_2020-05-25_15-05-09](https://user-images.githubusercontent.com/10961196/82811324-28ce1200-9e99-11ea-92d7-d7bcb7180870.jpg)
У меня вообще картинка не подгружается

**Comment by epogrebnyak** [comment]
У меня так:

![изображение](https://user-images.githubusercontent.com/9265326/82812591-ff62b580-9e9b-11ea-9030-d49c13733a5c.png)

**Comment by epogrebnyak** [comment]
https://stackoverflow.com/questions/19778620/provide-an-image-for-whatsapp-link-sharing

**Comment by kyrsquir** [comment]
https://github.com/squidfunk/mkdocs-material/issues/663#issuecomment-357743267

**Comment by kyrsquir** [comment]
https://github.com/squidfunk/mkdocs-material/issues/663#issuecomment-357743267
