### ISSUE TITLE
макет: поменять цвет верхней полоски

### ISSUE THREAD

**Issue by epogrebnyak** [finec-mgimo/preview#2]
Образец цвета:
![изображение](https://user-images.githubusercontent.com/9265326/82724359-24112e80-9cde-11ea-9191-a92b35d976bb.png)

Moжно переключить палитру, но там нет точного цвета: 
https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette

Либо, скорее всего, добавлять в что-то CSS:
https://squidfunk.github.io/mkdocs-material/customization/

**Comment by kyrsquir** [comment]
Добавил файл `source/css/extra.css`, в соответствии с инструкцией
https://www.mkdocs.org/user-guide/configuration/#extra_css
